### ISSUE TITLE
Version 0.10.1 release plans

### ISSUE THREAD

**Issue by murrayrm** [python-control/python-control#1020]
This issue is intended to track changes that will be part of the version 0.10.1 release of python-control.  There are a number of changes that will be part of this:

* [x] NumPy 2.0 compatibility
* [x] Bug fixes for v0.10.0 (and earlier releases)
* Updates to various plotting routines, to provide a more consistent interface to the response/plot pattern implemented in version 0.10.
   - [x] #996 
   - [x] #997
   - [x] #1011
   - [x] #1018
   - [x] More uniform interface (#1034)
   - [x] More consistent handling of tickmark labels (see comments in #1034; PR #1040).
* [x] Various small improvements to signal/system naming in `nlsys` (#1019)
* [x] New examples (in the style of control tutorials): these are the `example/cds110_*.ipynb` notebooks, which I plan to rename to be of the form `examples/cds110-Ln_*.ipynb`, where `n` is an ordering in case you want to go through them one by one.  (#1037)
* [x] Documentation updates: make sure all arguments are documented, deprecated functions are processed in a uniform way.  (#1038)

I hope to get this released by end of July, so that anyone using python-control for fall courses has the latest version.

Thoughts on other things we should take care of in this release are welcome.

**Comment by murrayrm** [comment]
Planning on doing the 0.10.1 release in the coming days.  Let me know if there is anything else critical that we should add before sending that out...

**Comment by murrayrm** [comment]
0.10.1 released!
