### ISSUE TITLE
Version 0.10 changes (tracking issue)

### ISSUE THREAD

**Issue by murrayrm** [python-control/python-control#917]
This issue is intended to track changes that will be part of the version 0.10 release of python-control.  This change in the minor version number will enable changes to the user interface, so this is a good time to make changes we have been discussing for a while:

Planned changes (and status):
* [x] Add in the new multivariable interconnect functionality (done in #881)
* [x] Get rid of support for the NumPy matrix class (no longer recommended by NumPy, though not yet deprecated; done in #913)
* [x] Restructure I/O system classes (see #904; done in #916)
* Separate out plotting functions (see #645)
    * [x] Time plotting function (initial, step, impulse, forced respond) (#920)
    * [x] Frequency plotting functions (bode, nyquist) (#924)
    * [x] Pole-zero plotting functions (pzmap, rlocus) (#953)
* [x] Create factory function for flat systems (perhaps part of #916)

**Comment by murrayrm** [comment]
I've taken a first crack at implementing the new plotting paradigm (#645) for the time response functions.  The following code
```
sys = ct.rss(4, 2, 2)
ct.step_response(sys).plot()
```
now produces:
![step_response](https://github.com/python-control/python-control/assets/293362/57202ff6-be08-48ee-bcf5-e37124edd6d2)

There are lots of options for changing around the way things plot, allowing multiple calls (which plot on the same axes), and more.  Some preliminary documentation is [here](https://murrayrm-python-control.readthedocs.io/en/time_plots-20jun2023/plotting.html).

I'll post this as a PR as soon as #916 gets merged into the main branch (since this set of changes builds on that one).

**Comment by murrayrm** [comment]
The initial set of plotting changes are now done.  I am playing around a bit with `phase_plot`, which is a very kludgy function for generating phase portraits.  It might be useful to include that in the set of _response/_plot changes, but it is not really quite the same, so might be something to save for later.

**Comment by murrayrm** [comment]
The changes in phaseplot are now done (#980).  Planning to release v0.10.0 in the coming days.
